### ISSUE TITLE
react 0.13.x?

### ISSUE THREAD

**Issue by sogko** [Zinggi/RAnimation#1]
Hey there,

I wanted to give this package a try but I can't `npm install` it due to the package specifiying `react@0.12.x` as its peer dependency.

Is there a chance that this would work with v0.13.x? If so, can the package.json be updated to allow it to be used with v0.13.x?

Thanks!

**Comment by Zinggi** [comment]
This will most likely still work with react 0.13, but I couldn't test anything yet, so I can't guarantee anything.
I just didn't had the time yet to look at react 0.13 as I was on holidays and still am.

You could try it on its own and see if everything still works with 0.13 and if so, send me a pull request and I'll accept it.
Or wait about 1 month till I'm back and I'll have a look at it then.

Sorry I can't be of more help now.
Cheers!

**Comment by lucasfeliciano** [comment]
@sogko did you tried with react 0.13?
Give us your thoughts

**Comment by sogko** [comment]
hey @lucasfeliciano 

I'm sorry I couldn't be of any help right now, I went with another route for my project (used `velocity-animate` instead, wrapping it around TransitionGroup). I may or may not revisit this when I have the chance though, no promises.

**Comment by lucasfeliciano** [comment]
@sogko Did it work for you?

I'm implementing the app using cordova + react but the animations are so slow on mobile.

I have a a list and when I sort this list it should animate the item going up on that list, I tried a lot of things which works ok in the browser but on mobile it is unacceptable slow.

So I'm looking for something that works on mobile, I tried a lot of things without success :(

@Zinggi I tried with react 0.13 but I got some problems.

1- I'm using coffee script and cjsx, so I had require the right files with explicit extensions (.cjsx) .
2- After solving problem 1 
I'm having this error `Uncaught SyntaxError: Unexpected token )`
error on this line above:

``` javascript
var nowInSeconds = () => window.performance.now() / 1000;
```

https://github.com/Zinggi/RAnimation/blob/master/src/animation/animationMixin.jsx#L11

**Comment by Zinggi** [comment]
Hey there,
sorry that I didn't reply earlier, I got back from my holidays some time ago, but I didn't got around to dedicate any time to this.
I will have a closer look at it today.

@lucasfeliciano the problem you're having is because I don't really know how best to publish this library. I'm using jsx syntax with the harmony option, so you would have to activate the harmony switch to get it working.
However I don't think this is the right way to do it. The best option would be if I could publish an already compiled version that doesn't require jsx or harmony, just plain JavaScript.
But I don't know how I could do this. Anyone knows how?

**Comment by Zinggi** [comment]
I just noticed that this library doesn't depend on react at all!
It was developed with react in mind, but it's just a mixin and therefore doesn't need react.
The only thing that uses react are the examples.

I'm just going to remove react from its peer-dependencies, simple solution.
Also instead of trying to compile harmony to plain JS, I think I'm just going to rewrite it to plain old JS, this would solve the second problem.

**Comment by Zinggi** [comment]
Alright, it should work now.
Could you please confirm @lucasfeliciano ?

**Comment by lucasfeliciano** [comment]
@Zinggi Sure, I'll do that after lunch and I give you the feedback.

Thank you for the fast reply and fix. :+1:

**Comment by lucasfeliciano** [comment]
@Zinggi I had to change the extension of the main file into the package.json.

After I that, I could use your module.

But It it still not smooth on a Nexus 5.

Here is my code that I'm running on the mobile with cordova.
Am I missing something?

``` coffeescript
React = require "react"
{animationMixin, Model} = require "r-animation"

bla = [0,1,2,3,4,5,6]
# bla = [0,1,2]

RAnimatetest = React.createClass
  mixins: [animationMixin]
  componentDidMount:->
    console.log 'componentDidMount'

  getInitialAnimationState: ->
    x: 0
    forwards: true

  render: ->
    <div style={{height:"100%"}}>
      <button className="button blue" onClick={@animateBall}>
        Animate!
      </button>
      {for key in bla
        <div ref={"ball_" + key} style={{
          backgroundColor:"rgba(255,255,0,0.9)", 
          width: "50px", 
          top: (key + 1) * 60 + 'px', 
          height: "50px", 
          borderRadius: "10px", 
          position: "absolute"}} />
      }
    </div>

  performAnimation: ->
    console.log 'performAnimation'
    # node = @refs.ball.getDOMNode()
    # node.style.left = (@animationState.x * 70 + 15) + "%"

    # node2 = @refs.ball2.getDOMNode()
    # node2.style.left = (@animationState.x * 50 + 15) + "%"

    for key in bla
      # console.log 'aaaa test', key
      # console.log @refs
      @refs['ball_' + key].getDOMNode().style.left = (@animationState.x * (40 + (key * 2)) + (key + 5)) + "%"


  animateBall: ->
    end = if @animationState.forwards then 1 else 0
    @easeTo x:
      endValue: end
      # modelFn: Model.controlled.underDamped
    @animationState.forwards = !@animationState.forwards
    return

module.exports = RAnimatetest

```

**Comment by Zinggi** [comment]
Yes, this can be slightly improved.
Use `style.transform = "translate3d(x,0,0)"` instead of `style.left = x`. (don't forget the prefixes)
This should improve performance greatly, but I didn't test it with your example.
Also, remove the `console.log`.

Here's a great article on animation performance:
http://www.html5rocks.com/en/tutorials/speed/high-performance-animations/

It's very hard to get smooth animations on mobile.
I think this library should probably also include some helper functions to use in the performAnimation function to prevent common mistakes.
And my examples should be improved as well, since they're using `style.left` too...

**Comment by lucasfeliciano** [comment]
Thank you a lot for the article.
I'm coming from a backend background so I'm not a animation expert.
I'll try those changes now and I'll be right back with an feedback :)

Thank you one more time.

**Comment by lucasfeliciano** [comment]
Indeed I got a great performance improvement.
It is not 100% yet but I can live with that.

Thank you a lot @Zinggi !

**Comment by Zinggi** [comment]
Glad that did it. More will be hard to get on a mobile browser. A native implementation seems to be the only way to get the best performance.
